### ISSUE TITLE
Unable to run the code

### ISSUE THREAD

**Issue by aniketp** [Sunil02324/Instagram-Image-Downloader#1]
On trying to run the code it shows the following error : Missing parentheses in call to Print 
![screenshot from 2017-02-19 19-17-13](https://cloud.githubusercontent.com/assets/24573641/23102929/1b50cb84-f6d8-11e6-8a6b-67a17fd35dfa.png)

**Comment by Sunil02324** [comment]
This code runs with Python2. I guess you are trying to run with python3. Please check it.

**Comment by aniketp** [comment]
Thanks , it worked :)
